// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Activity struct {
	ID        string
	ProjectID string
	DispName  string
	Duration  int64
}

type Dependency struct {
	ID                    string
	ProjectID             string
	Relationship          string
	PredecessorActivityID string
	SuccessorActivityID   string
}

type Project struct {
	ID       string
	DispName string
}
