// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"
)

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const findAllProjects = `-- name: FindAllProjects :many
SELECT id, disp_name FROM projects
`

func (q *Queries) FindAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, findAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.DispName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProjectById = `-- name: FindProjectById :one
SELECT id, disp_name FROM projects WHERE id = ?
`

func (q *Queries) FindProjectById(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, findProjectById, id)
	var i Project
	err := row.Scan(&i.ID, &i.DispName)
	return i, err
}

const findProjectByName = `-- name: FindProjectByName :many
SELECT id, disp_name FROM projects WHERE disp_name LIKE ?
`

func (q *Queries) FindProjectByName(ctx context.Context, dispName string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, findProjectByName, dispName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.DispName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (id, disp_name) VALUES (?, ?)
RETURNING id, disp_name
`

type InsertProjectParams struct {
	ID       string
	DispName string
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, insertProject, arg.ID, arg.DispName)
	var i Project
	err := row.Scan(&i.ID, &i.DispName)
	return i, err
}
